---
title: "Introduction to rpkgtutorial"
author: "Yang Zhang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to rpkgtutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This package provides two helper functions that provide summary and visualization on certain type of data files. 

* Internval functions
    * `fars_read(filename)` - Read data from a csv file
    * `make_filename()` - Generate a file name in a specific convension
    * `fars_read_years()` - Read data from multiple csv files
* External functions:
    * `fars_summarize_years()` - Count number of accidents happend in each month and year
    * `fars_map_state()` - Plot the locations of accidents happend in a given state and year
    
## Data Files

In order to execute the functions properly, data files need to be placed in the current working directory with a naming convension of `accident_yyyy.csv.bz2`, where `yyyy` indicates a year. Sample data files can be found in the pacakge's `extdata` folder.

## Example
```{r eval = FALSE}
# Get specific columns from each data file
fars_summarize_years(c(2013, 2014, 2015))

# Plot a map to show the location of accidents recorded in the data file
fars_map_state(4, 2013)
```
